### ISSUE TITLE
[Discussion] Dialog box displays garbled characters

### ISSUE THREAD

**Issue by alvin1221** [emqx/MQTTX#506]
#### What did I do

open ssl file;

#### What happened

The dialog box displays garbled characters

#### Environment

- OS: OS version, e.g. Ubuntu 20.10
- MQTTX version, e.g. v1.5.1

#### More detail

More detail include `log` information or screenshot

[2021-02-08T17:08:47.370] [INFO] default - APP init
Gtk-Message: 17:09:32.688: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 17:09:43.915: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 17:10:09.514: GtkDialog mapped without a transient parent. This is discouraged.

Gtk-Message: 17:31:40.216: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by ysfscream** [comment]
Hi, thanks for your feedback! Could you please upload a screenshot? :)

**Comment by alvin1221** [comment]
https://user-images.githubusercontent.com/68314044/107243048-95109600-6a67-11eb-9610-0ff86af81943.MOV

**Comment by alvin1221** [comment]
![Uploading 61C10604-3D81-4774-8398-C602C472F91C.png…]()

**Comment by alvin1221** [comment]
![321594CF-BBB3-412E-9433-6E4F4949E2D3](https://user-images.githubusercontent.com/68314044/107244158-ac9c4e80-6a68-11eb-9c83-8a00847937c3.png)

**Comment by oceanlvr** [comment]
@alvin1221 Thanks for your feedback.
I cannot reproduce this error locally. Could you please tell me your `Gnome` version? I strongly believe that it is caused by the `electron` itself.

![image](https://user-images.githubusercontent.com/36698124/107249608-7a8deb00-6a6e-11eb-9100-3450ddb0b260.png)

**Comment by oceanlvr** [comment]
Here are some reference issues: [https://github.com/electron/electron/issues/12423](https://github.com/electron/electron/issues/12423).
And I think this problem lead by your `Gnome` version. Maybe you should update your Gnome.

This reply may help you, I think it caused by `Gnome`

https://github.com/electron/electron/issues/12423#issuecomment-699510600

**Comment by oceanlvr** [comment]
@alvin1221 please tell us, what's your `gnome` version. 

```
gnome-shell --version
```

We are expecting your reply. :)

**Comment by alvin1221** [comment]
GNOME Shell 3.38.1

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by oceanlvr** [comment]
@alvin1221 Hi, I download the `Ubuntu 20.10` and try `MQTT X v1.5.1`:
![image](https://user-images.githubusercontent.com/36698124/107325236-64bb0d00-6ae4-11eb-9a2e-9882ea8b4813.png)

Dialog box works normal for me.
It's an opening issue in the `electron`. Not everyone will have this problem.
I won't take action util this issue has been solved https://github.com/electron/electron/issues/12423

**Comment by oceanlvr** [comment]
Maybe you can reinstall `MQTT X` with:

```
snap install `your-local-MQTTX.snap` --dangerous
```

**Comment by alvin1221** [comment]
Hi， I have already removed MQTTX first, and execute `"snap install `your-local-MQTTX.snap` --dangerous"`, but the same problem still exists;

**Comment by oceanlvr** [comment]
@alvin1221 
Maybe you can try to upgrade `Gnome`, this problem is caused by the system and the electron environment and I can't reproduce this problem in my machine, we are sorry about we can't take action or give you more suggestions under so less information.

**Comment by alvin1221** [comment]
OK ,I'll try it later

**Comment by oceanlvr** [comment]
Same problem as:
https://github.com/zulip/zulip-desktop/issues/932
https://github.com/electron/electron/issues/17079

**Comment by ysfscream** [comment]
If there is nothing wrong, I will close this issue.
